services:
  postgres:
    container_name: auction-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=AuctionDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d AuctionDb"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data

volumes:
  postgres_data:
  mongodata:
